
var forms = [

	{
	id: 2,
	name: "HIV Test Kits Report and Order form",
	completed: false,
	sections: [
			{
			id: 0, 
			name: "Commodity report",
			completed: false,
			commodities: [ 
					{
					id: 1,
					name: "Determine HIV 1/2",
					explanationText: "(Includes 1 bottle of Chase Buffer per 100 tests)",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									programIndicatorId: 4,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									programIndicatorId: 5,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 2,
					name: "Stat-Pak HIV 1/2",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},				
				{
					id: 3,
					name: "Unigold HIV 1/2",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 4,
					name: "Vaccutainer tubes",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 5,
					name: "Vaccutainer Holders",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 6,
					name: "Needles/Lancets",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 7,
					name: "Pasteur Pipette",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 8,
					name: "DBS Collection kits (items of 50 samples)",
					basicUnit: "Kit",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
			],
		},
		{
			id: 1,
			name: "Bimonthly Summary of HIV Test by Purpose of Use",
			completed: false,
			commodities: [ 
				{
					id: 1,
					name: "Determine HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements: [
									{ 
										name: "HCT",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "PMTCT",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "Clinical Diagnosis",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "Quality Control",
										type: "Number",
										calculated: false,
										required: true,
									},
								],
				},
				{
					id: 2,
					name: "Stat-Pak HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements:
										[
							{ 
								name: "HCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "PMTCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Clinical Diagnosis",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Quality Control",
								type: "Number",
								calculated: false,
								required: true,
							},
						],
				},
				{
					id: 3,
					name: "Unigold HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements: [
							{ 
								name: "HCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "PMTCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Clinical Diagnosis",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Quality Control",
								type: "Number",
								calculated: false,
								required: true,
							},
						],
				},
			],
		},
	]},
	{
	id: 3,
	name: "ARV order and report",
	completed: false,
	approved: false,
	sections: [
			{
			id: 0, 
			name: "Commodity report",
			completed: false,
			commodities: [ 
					{
					id: 1,
					name: "Determine HIV 1/2 (Includes 1 bottle of Chase Buffer per 100 tests)",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3,
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
									value: 40,
								},
								{ 
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 2,
					name: "Stat-Pak HIV 1/2",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},				
				{
					id: 3,
					name: "Unigold HIV 1/2",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 4,
					name: "Vaccutainer tubes",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 5,
					name: "Vaccutainer Holders",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 6,
					name: "Needles/Lancets",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 7,
					name: "Pasteur Pipette",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 8,
					name: "DBS Collection kits (items of 50 samples)",
					basicUnit: "Kit",
					completed: false,
					dataElements: [
								{ 
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
			],
		},
		{
			id: 1,
			name: "Bimonthly Summary of HIV Test by Purpose of Use",
			completed: false,
			commodities: [ 
				{
					id: 1,
					name: "Determine HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements: [
									{ 
										name: "HCT",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "PMTCT",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "Clinical Diagnosis",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "Quality Control",
										type: "Number",
										calculated: false,
										required: true,
									},
								],
				},
				{
					id: 2,
					name: "Stat-Pak HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements:
										[
							{ 
								name: "HCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "PMTCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Clinical Diagnosis",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Quality Control",
								type: "Number",
								calculated: false,
								required: true,
							},
						],
				},
				{
					id: 3,
					name: "Unigold HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements: [
							{ 
								name: "HCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "PMTCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Clinical Diagnosis",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Quality Control",
								type: "Number",
								calculated: false,
								required: true,
							},
						],
				},
			],
		},
	]}
];

var cycles = [
	
	{
		id: 1, 
		forms: [
		{
	id: 2,
	name: "HIV Test Kits Report and Order form",
	completed: false,
	sections: [
			{
			id: 0, 
			name: "Commodity report",
			completed: false,
			commodities: [ 
					{
					id: 1,
					name: "Determine HIV 1/2",
					explanationText: "(Includes 1 bottle of Chase Buffer per 100 tests)",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									programIndicatorId: 4,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									programIndicatorId: 5,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 2,
					name: "Stat-Pak HIV 1/2",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},				
				{
					id: 3,
					name: "Unigold HIV 1/2",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 4,
					name: "Vaccutainer tubes",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 5,
					name: "Vaccutainer Holders",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 6,
					name: "Needles/Lancets",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 7,
					name: "Pasteur Pipette",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 8,
					name: "DBS Collection kits (items of 50 samples)",
					basicUnit: "Kit",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
			],
		},
		{
			id: 1,
			name: "Bimonthly Summary of HIV Test by Purpose of Use",
			completed: false,
			commodities: [ 
				{
					id: 1,
					name: "Determine HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements: [
									{ 
										name: "HCT",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "PMTCT",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "Clinical Diagnosis",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "Quality Control",
										type: "Number",
										calculated: false,
										required: true,
									},
								],
				},
				{
					id: 2,
					name: "Stat-Pak HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements:
										[
							{ 
								name: "HCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "PMTCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Clinical Diagnosis",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Quality Control",
								type: "Number",
								calculated: false,
								required: true,
							},
						],
				},
				{
					id: 3,
					name: "Unigold HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements: [
							{ 
								name: "HCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "PMTCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Clinical Diagnosis",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Quality Control",
								type: "Number",
								calculated: false,
								required: true,
							},
						],
				},
			],
		},
	]},
	{
	id: 3,
	name: "Tuberculosis and Leprosy medicine Report and Order form",
	completed: true,
	approved: true,
	sections: [
			{
			id: 0, 
			name: "Commodity report",
			completed: false,
			commodities: [ 
					{
					id: 1,
					name: "Determine HIV 1/2",
					explanationText: "(Includes 1 bottle of Chase Buffer per 100 tests)",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									programIndicatorId: 4,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									programIndicatorId: 5,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 2,
					name: "Stat-Pak HIV 1/2",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},				
				{
					id: 3,
					name: "Unigold HIV 1/2",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 4,
					name: "Vaccutainer tubes",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 5,
					name: "Vaccutainer Holders",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 6,
					name: "Needles/Lancets",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 7,
					name: "Pasteur Pipette",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 8,
					name: "DBS Collection kits (items of 50 samples)",
					basicUnit: "Kit",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
			],
		},
		{
			id: 1,
			name: "Bimonthly Summary of HIV Test by Purpose of Use",
			completed: false,
			commodities: [ 
				{
					id: 1,
					name: "Determine HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements: [
									{ 
										name: "HCT",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "PMTCT",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "Clinical Diagnosis",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "Quality Control",
										type: "Number",
										calculated: false,
										required: true,
									},
								],
				},
				{
					id: 2,
					name: "Stat-Pak HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements:
										[
							{ 
								name: "HCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "PMTCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Clinical Diagnosis",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Quality Control",
								type: "Number",
								calculated: false,
								required: true,
							},
						],
				},
				{
					id: 3,
					name: "Unigold HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements: [
							{ 
								name: "HCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "PMTCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Clinical Diagnosis",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Quality Control",
								type: "Number",
								calculated: false,
								required: true,
							},
						],
				},
			],
		},
	]},
   {
	id: 4,
	name: "ARV Report and Order form",
	completed: false,
	sections: [
			{
			id: 0, 
			name: "Commodity report",
			completed: false,
			commodities: [ 
					{
					id: 1,
					name: "Determine HIV 1/2",
					explanationText: "(Includes 1 bottle of Chase Buffer per 100 tests)",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									programIndicatorId: 4,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									programIndicatorId: 5,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 2,
					name: "Stat-Pak HIV 1/2",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},				
				{
					id: 3,
					name: "Unigold HIV 1/2",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 4,
					name: "Vaccutainer tubes",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 5,
					name: "Vaccutainer Holders",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 6,
					name: "Needles/Lancets",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 7,
					name: "Pasteur Pipette",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 8,
					name: "DBS Collection kits (items of 50 samples)",
					basicUnit: "Kit",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
			],
		},
		{
			id: 1,
			name: "Bimonthly Summary of HIV Test by Purpose of Use",
			completed: false,
			commodities: [ 
				{
					id: 1,
					name: "Determine HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements: [
									{ 
										name: "HCT",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "PMTCT",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "Clinical Diagnosis",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "Quality Control",
										type: "Number",
										calculated: false,
										required: true,
									},
								],
				},
				{
					id: 2,
					name: "Stat-Pak HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements:
										[
							{ 
								name: "HCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "PMTCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Clinical Diagnosis",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Quality Control",
								type: "Number",
								calculated: false,
								required: true,
							},
						],
				},
				{
					id: 3,
					name: "Unigold HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements: [
							{ 
								name: "HCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "PMTCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Clinical Diagnosis",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Quality Control",
								type: "Number",
								calculated: false,
								required: true,
							},
						],
				},
			],
		},
	]}
	
	],
	},
	
	{
		id: 2, 
		forms: 
		[{
			id: 2,
		name: "HIV Test Kits Report and Order form",
		completed: true,
		approved: true,
		sections: [
			{
			id: 0, 
			name: "Commodity report",
			completed: true,
			commodities: [ 
					{
					id: 1,
					name: "Determine HIV 1/2",
					explanationText: "(Includes 1 bottle of Chase Buffer per 100 tests)",
					basicUnit: "1 test",
					completed: true,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
									value: 45,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
									value: 50,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
									value: 80,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
									value: 10,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									programIndicatorId: 4,
									required: true,
									value: 25,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									programIndicatorId: 5,
									required: true,
									value: 160,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
									value: 135,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
									value: 135,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
									value: "",
								}
							],
				},
				{
					id: 2,
					name: "Stat-Pak HIV 1/2",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
									value: 45,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
									value: 50,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
									value: 80,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
									value: 10,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									programIndicatorId: 4,
									required: true,
									value: 25,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									programIndicatorId: 5,
									required: true,
									value: 160,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
									value: 135,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
									value: 135,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
									value: "",
								}
							],
				},				
				{
					id: 3,
					name: "Unigold HIV 1/2",
					basicUnit: "1 test",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
									value: 45,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
									value: 50,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
									value: 80,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
									value: 10,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									programIndicatorId: 4,
									required: true,
									value: 25,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									programIndicatorId: 5,
									required: true,
									value: 160,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
									value: 135,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
									value: 135,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
									value: "",
								}
							],
				},
				{
					id: 4,
					name: "Vaccutainer tubes",
					basicUnit: "1pc",
					completed: false,
					notApplicable: true,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
									value: 45,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
									value: 50,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
									value: 80,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
									value: 10,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									programIndicatorId: 4,
									required: true,
									value: 25,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									programIndicatorId: 5,
									required: true,
									value: 160,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
									value: 135,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
									value: 135,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
									value: "",
								}
							],
				},
				{
					id: 5,
					name: "Vaccutainer Holders",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
									value: 45,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
									value: 50,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
									value: 80,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
									value: 10,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									programIndicatorId: 4,
									required: true,
									value: 25,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									programIndicatorId: 5,
									required: true,
									value: 160,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
									value: 135,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
									value: 135,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
									value: "",
								}
							],
				},
				{
					id: 6,
					name: "Needles/Lancets",
					basicUnit: "1pc",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
									value: 45,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
									value: 50,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
									value: 80,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
									value: 10,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									programIndicatorId: 4,
									required: true,
									value: 25,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									programIndicatorId: 5,
									required: true,
									value: 160,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
									value: 135,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
									value: 135,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
									value: "",
								}
							],
				},
				{
					id: 7,
					name: "Pasteur Pipette",
					basicUnit: "1pc",
					completed: false,
					notApplicable: true,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: false,
									required: true,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									required: true,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
								}
							],
				},
				{
					id: 8,
					name: "DBS Collection kits (items of 50 samples)",
					basicUnit: "Kit",
					completed: false,
					dataElements: [
								{ 
									id: 0,
									name: "Opening balance",
									type: "Number",
									calculated: false,
									required: true,
									getDataFromElementInPreviousCycle: 4,
									value: 45,
								},
								{ 
									id: 1,
									name: "Quantity received",
									type: "Number",
									calculated: false,
									required: true,
									value: 50,
								},
								{ 
									id: 2,
									name: "Test consumption",
									type: "Number",
									calculated: false,
									required: true,
									value: 80,
								},
								{ 
									id: 3, 
									name: "Losses / Adjustments",
									type: "Number",
									calculated: false,
									required: true,
									value: 10,
								},
								{ 
									id: 4,
									name: "Number of tests remaining",
									type: "Number",
									calculated: true,
									programIndicatorId: 4,
									required: true,
									value: 25,
								},
								{ 
									id: 5,
									name: "Maximum stock quantity",
									type: "Number",
									calculated: true,
									programIndicatorId: 5,
									required: true,
									value: 160,
								},						
								{ 
									id: 6,
									name: "Quantity Required",
									type: "Number",
									calculated: true,
									required: true,
									value: 135,
								},							
								{ 
									id: 7,
									name: "Quantity to ship",
									type: "Number",
									calculated: false,
									required: true,
									value: 135,
								},						
								{ 
									id: 8,
									name: "Notes",
									type: "Text",
									calculated: false,
									required: true,
									value: "",
								}
							],
				},
			],
		},
		{
			id: 1,
			name: "Bimonthly Summary of HIV Test by Purpose of Use",
			completed: false,
			commodities: [ 
				{
					id: 1,
					name: "Determine HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements: [
									{ 
										name: "HCT",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "PMTCT",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "Clinical Diagnosis",
										type: "Number",
										calculated: false,
										required: true,
									},
									{ 
										name: "Quality Control",
										type: "Number",
										calculated: false,
										required: true,
									},
								],
				},
				{
					id: 2,
					name: "Stat-Pak HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements:
										[
							{ 
								name: "HCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "PMTCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Clinical Diagnosis",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Quality Control",
								type: "Number",
								calculated: false,
								required: true,
							},
						],
				},
				{
					id: 3,
					name: "Unigold HIV 1/2",
					basicUnit: "",
					completed: false,
					dataElements: [
							{ 
								name: "HCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "PMTCT",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Clinical Diagnosis",
								type: "Number",
								calculated: false,
								required: true,
							},
							{ 
								name: "Quality Control",
								type: "Number",
								calculated: false,
								required: true,
							},
						],
				},
			],
		},
	]},],
	},

];

var facilities = [
	{
		id: 0,
		name: "Kawaala Health Center III",
		cycles: cycles,
	},
	{
		id: 1,
		name: "Kiswa Health Center IV",
		cycles: cycles,
	}
];
